"""Story 2.5: Styled ASS subtitle generator for Korean prayer shorts.

Converts script AST (title, scripture, prayer blocks) + timing.json into
a valid ASS subtitle file with:
- Title/scripture at top (alignment 8, safe area margins)
- Prayer blocks centred (alignment 5, fade in/out)
- 아멘 last block: 2s hold + 0.5s fade-out

No file I/O in the pure generator; `generate_subtitles` handles writing.
"""
from __future__ import annotations

import re
from pathlib import Path
from typing import Any

from .config import SubtitleConfig, DEFAULT_SUBTITLE_CONFIG

# ─────────────────────── error type ────────────────────────

class SubtitleError(Exception):
    """Raised for validation failures before ASS generation succeeds."""

    def __init__(self, error_code: str, message: str) -> None:
        super().__init__(message)
        self.error_code = error_code


# ─────────────────────── text utilities ────────────────────────

def _escape_ass(text: str) -> str:
    """Escape ASS special characters and convert newlines to \\N.

    Strips carriage returns before conversion so CRLF input does not leave
    stray \\r characters in the output Dialogue text field.
    """
    text = text.replace("\r", "")
    text = text.replace("{", "\\{").replace("}", "\\}")
    text = text.replace("\n", "\\N")
    return text


def _format_time(seconds: float) -> str:
    """Convert seconds to ASS timestamp H:MM:SS.CC (centiseconds).

    Clamps negative input to 0 so upstream alignment errors do not produce
    invalid (negative) ASS timestamps.
    """
    seconds = max(0.0, seconds)
    total_cs = round(seconds * 100)
    h = total_cs // 360000
    total_cs %= 360000
    m = total_cs // 6000
    total_cs %= 6000
    s = total_cs // 100
    cs = total_cs % 100
    return f"{h}:{m:02d}:{s:02d}.{cs:02d}"


def _is_supported_char(ch: str) -> bool:
    """Return True if the character is printable ASCII, Hangul, or common punctuation.

    Line separators (\n, \r) are formatting characters converted by _escape_ass,
    not rendered glyphs, so they are always accepted.
    """
    cp = ord(ch)
    # Line separators: structural, not rendered as glyphs
    if ch in "\r\n":
        return True
    # Printable ASCII only (0x20 space to 0x7E tilde); reject other control chars
    if 0x20 <= cp <= 0x7E:
        return True
    # Hangul syllables
    if 0xAC00 <= cp <= 0xD7A3:
        return True
    # Hangul Jamo
    if 0x1100 <= cp <= 0x11FF:
        return True
    # Hangul compatibility Jamo
    if 0x3130 <= cp <= 0x318F:
        return True
    # Common CJK punctuation used in Korean text
    if cp in (0x3002, 0x300C, 0x300D, 0xFF0C, 0xFF01, 0xFF1F, 0x2026):
        return True
    return False


def _validate_glyphs(text: str) -> list[str]:
    """Return list of unsupported characters found in text."""
    return [ch for ch in text if not _is_supported_char(ch)]


def _is_amen_text(text: str) -> bool:
    """Return True if text ends with 아멘 (with optional trailing punctuation)."""
    stripped = re.sub(r"[\s\.,!?·…\n]+$", "", text)
    return stripped.endswith("아멘")


def _block_lines(block: dict[str, Any]) -> list[str]:
    """Return lines list from a block dict (uses 'lines' key, falls back to text split)."""
    if "lines" in block:
        return block["lines"]
    return block.get("text", "").split("\n")


# ─────────────────────── validation ────────────────────────

def _validate(
    script_ast: dict[str, Any],
    timing: dict[str, Any],
    config: SubtitleConfig,
    font_path: Path | None,
) -> None:
    """Raise SubtitleError for any pre-generation validation failure."""
    if font_path is not None and not font_path.is_file():
        raise SubtitleError("FONT_NOT_FOUND", f"폰트 파일을 찾을 수 없습니다: {font_path}")

    # Validate glyphs in title, scripture, AND prayer blocks
    texts_to_check = [
        script_ast.get("title", ""),
        script_ast.get("scripture", ""),
        *[block.get("text", "") for block in timing.get("subtitleBlocks", [])],
    ]
    all_text = " ".join(texts_to_check)
    unsupported = _validate_glyphs(all_text)
    if unsupported:
        chars = ", ".join(repr(c) for c in sorted(set(unsupported)))
        raise SubtitleError(
            "GLYPH_NOT_SUPPORTED",
            f"한글 폰트가 지원하지 않는 문자가 포함되어 있습니다: {chars}",
        )

    for block in timing.get("subtitleBlocks", []):
        lines = _block_lines(block)
        if len(lines) > config.max_prayer_lines:
            raise SubtitleError(
                "SAFE_AREA_EXCEEDED",
                f"블록 {block.get('index')}의 라인 수({len(lines)})가 "
                f"safe area 최대 허용({config.max_prayer_lines})을 초과합니다.",
            )


# ─────────────────────── ASS sections ────────────────────────

def _script_info(config: SubtitleConfig) -> str:
    return (
        "[Script Info]\n"
        "; Generated by Gracetree Shorts Studio\n"
        "ScriptType: v4.00+\n"
        f"PlayResX: {config.play_res_x}\n"
        f"PlayResY: {config.play_res_y}\n"
        "WrapStyle: 0\n"
        "ScaledBorderAndShadow: yes\n"
    )


def _styles(config: SubtitleConfig) -> str:
    fmt = "Format: Name, Fontname, Fontsize, PrimaryColour, SecondaryColour, OutlineColour, BackColour, Bold, Italic, Underline, StrikeOut, ScaleX, ScaleY, Spacing, Angle, BorderStyle, Outline, Shadow, Alignment, MarginL, MarginR, MarginV, Encoding"
    mh = config.margin_h
    mv = config.margin_v_top

    def _style(name: str, size: int, color: str, alignment: int, margin_v: int) -> str:
        # Bold=0: Black Han Sans is already a black weight; synthetic bold would
        # fill in counters and look blobby. Use the font's natural weight.
        return (
            f"Style: {name},{config.font_name},{size},{color},&H000000FF,"
            f"{config.color_outline},{config.color_shadow},"
            f"0,0,0,0,100,100,0,0,1,"
            f"{config.outline_thickness},{config.shadow_depth},"
            f"{alignment},{mh},{mh},{margin_v},1"
        )

    scripture_v = mv + config.font_size_title + config.title_scripture_gap
    return (
        "[V4+ Styles]\n"
        f"{fmt}\n"
        f"{_style('Title', config.font_size_title, config.color_title, 8, mv)}\n"
        f"{_style('Scripture', config.font_size_scripture, config.color_scripture, 8, scripture_v)}\n"
        f"{_style('Prayer', config.font_size_prayer, config.color_prayer, 5, 0)}\n"
    )


def _dialogue(
    start: float,
    end: float,
    style: str,
    text: str,
    fade_in: int,
    fade_out: int,
    center: tuple[int, int] | None = None,
) -> str:
    # When `center` is given, anchor the text's middle (\an5) at that point so a
    # multi-line block stays centred there regardless of its height — used to keep
    # the title/scripture centred inside the intro black band.
    pos = f"\\pos({center[0]},{center[1]})\\an5" if center is not None else ""
    fad = f"{{{pos}\\fad({fade_in},{fade_out})}}"
    return (
        f"Dialogue: 0,{_format_time(start)},{_format_time(end)},"
        f"{style},,0,0,0,,{fad}{_escape_ass(text)}"
    )


def _events(
    script_ast: dict[str, Any],
    timing: dict[str, Any],
    config: SubtitleConfig,
) -> str:
    lines = [
        "[Events]",
        "Format: Layer, Start, End, Style, Name, MarginL, MarginR, MarginV, Effect, Text",
    ]

    timing_blocks = timing.get("subtitleBlocks", [])
    if timing_blocks:
        try:
            first_prayer_start = timing_blocks[0]["startTime"]
        except KeyError as exc:
            raise SubtitleError(
                "MISSING_TIMING",
                f"첫 번째 블록에 startTime이 없습니다: {exc}",
            ) from exc
    else:
        first_prayer_start = timing.get("voiceOffset", 2.0)

    # Title and scripture: shown sequentially (never on screen together) across
    # the intro window [0, first_prayer_start]. The title appears first, then the
    # scripture, each taking an equal slice. When only one is present it spans the
    # whole intro window.
    fi, fo = config.fade_in_ms, config.fade_out_ms
    intro = [
        (style, text)
        for style, text in (
            ("Title", script_ast.get("title", "")),
            ("Scripture", script_ast.get("scripture", "")),
        )
        if text.strip()
    ]
    band_center = (config.play_res_x // 2, config.title_band_center_v)
    if intro and first_prayer_start > 0:
        slot = first_prayer_start / len(intro)
        for k, (style, text) in enumerate(intro):
            seg_start = round(k * slot, 6)
            seg_end = first_prayer_start if k == len(intro) - 1 else round((k + 1) * slot, 6)
            lines.append(_dialogue(seg_start, seg_end, style, text, fi, fo, center=band_center))

    # Prayer blocks
    for i, block in enumerate(timing_blocks):
        is_last = (i == len(timing_blocks) - 1)
        text = block.get("text", "")
        try:
            start = block["startTime"]
            end = block["endTime"]
        except KeyError as exc:
            raise SubtitleError(
                "MISSING_TIMING",
                f"블록 {block.get('index', i)}에 타이밍 키가 없습니다: {exc}",
            ) from exc

        if is_last and _is_amen_text(text):
            end += config.amen_hold_seconds
            fade_out = config.amen_fade_out_ms
        else:
            fade_out = fo

        lines.append(_dialogue(start, end, "Prayer", text, fi, fade_out))

    return "\n".join(lines) + "\n"


# ─────────────────────── public API ────────────────────────

def generate_ass(
    script_ast: dict[str, Any],
    timing: dict[str, Any],
    config: SubtitleConfig = DEFAULT_SUBTITLE_CONFIG,
    font_path: Path | None = None,
) -> str:
    """Generate ASS subtitle content string.

    Parameters
    ----------
    script_ast: ScriptAstDto dict from Story 2.2 parser.
    timing: timing.json dict from Story 2.3 aligner.
    config: layout and styling config.
    font_path: optional path for font existence check (None = skip check).

    Returns
    -------
    ASS content as a UTF-8 string.

    Raises
    ------
    SubtitleError: FONT_NOT_FOUND, GLYPH_NOT_SUPPORTED, SAFE_AREA_EXCEEDED, MISSING_TIMING
    """
    _validate(script_ast, timing, config, font_path)
    parts = [
        _script_info(config),
        _styles(config),
        _events(script_ast, timing, config),
    ]
    return "\n".join(parts)


def generate_subtitles(
    script_ast: dict[str, Any],
    timing: dict[str, Any],
    attempt_dir: Path,
    config: SubtitleConfig = DEFAULT_SUBTITLE_CONFIG,
    font_path: Path | None = None,
) -> Path:
    """Generate and write subtitles.ass to attempt_dir.

    Raises SubtitleError if attempt_dir does not exist or on validation failure.
    """
    if not attempt_dir.is_dir():
        raise SubtitleError(
            "OUTPUT_DIR_MISSING",
            f"출력 디렉토리가 존재하지 않습니다: {attempt_dir}",
        )
    content = generate_ass(script_ast, timing, config, font_path)
    out = attempt_dir / "subtitles.ass"
    out.write_text(content, encoding="utf-8")
    return out
