"""Story 2.5: Styled ASS subtitle generator for Korean prayer shorts.

Converts script AST (title, scripture, prayer blocks) + timing.json into
a valid ASS subtitle file with:
- Title/scripture at top (alignment 8, safe area margins)
- Prayer blocks centred (alignment 5, fade in/out)
- 아멘 last block: 2s hold + 0.5s fade-out

No file I/O in the pure generator; `generate_subtitles` handles writing.
"""
from __future__ import annotations

import re
import unicodedata
from pathlib import Path
from typing import Any

from .config import SubtitleConfig, DEFAULT_SUBTITLE_CONFIG

# ─────────────────────── error type ────────────────────────

class SubtitleError(Exception):
    """Raised for validation failures before ASS generation succeeds."""

    def __init__(self, error_code: str, message: str) -> None:
        super().__init__(message)
        self.error_code = error_code


# ─────────────────────── text utilities ────────────────────────

def _escape_ass(text: str) -> str:
    """Escape ASS special characters and convert newlines to \\N."""
    text = text.replace("{", "\\{").replace("}", "\\}")
    text = text.replace("\n", "\\N")
    return text


def _format_time(seconds: float) -> str:
    """Convert seconds to ASS timestamp H:MM:SS.CC (centiseconds)."""
    total_cs = round(seconds * 100)
    h = total_cs // 360000
    total_cs %= 360000
    m = total_cs // 6000
    total_cs %= 6000
    s = total_cs // 100
    cs = total_cs % 100
    return f"{h}:{m:02d}:{s:02d}.{cs:02d}"


def _is_supported_char(ch: str) -> bool:
    """Return True if the character is ASCII, Hangul, or common punctuation."""
    cp = ord(ch)
    if cp <= 0x7E:  # ASCII
        return True
    # Hangul syllables
    if 0xAC00 <= cp <= 0xD7A3:
        return True
    # Hangul Jamo
    if 0x1100 <= cp <= 0x11FF:
        return True
    # Hangul compatibility Jamo
    if 0x3130 <= cp <= 0x318F:
        return True
    # Common CJK punctuation used in Korean text
    if cp in (0x3002, 0x300C, 0x300D, 0xFF0C, 0xFF01, 0xFF1F, 0x2026):
        return True
    return False


def _validate_glyphs(text: str) -> list[str]:
    """Return list of unsupported characters found in text."""
    unsupported = []
    for ch in text:
        if not _is_supported_char(ch):
            unsupported.append(ch)
    return unsupported


def _is_amen_text(text: str) -> bool:
    """Return True if text ends with 아멘 (with optional trailing punctuation)."""
    stripped = re.sub(r"[\s\.,!?·…\n]+$", "", text)
    return stripped.endswith("아멘")


# ─────────────────────── validation ────────────────────────

def _validate(
    script_ast: dict[str, Any],
    timing: dict[str, Any],
    config: SubtitleConfig,
    font_path: Path | None,
) -> None:
    """Raise SubtitleError for any pre-generation validation failure."""
    if font_path is not None and not font_path.is_file():
        raise SubtitleError("FONT_NOT_FOUND", f"폰트 파일을 찾을 수 없습니다: {font_path}")

    all_text = " ".join(
        block.get("text", "")
        for block in timing.get("subtitleBlocks", [])
    )
    unsupported = _validate_glyphs(all_text)
    if unsupported:
        chars = ", ".join(repr(c) for c in sorted(set(unsupported)))
        raise SubtitleError(
            "GLYPH_NOT_SUPPORTED",
            f"한글 폰트가 지원하지 않는 문자가 포함되어 있습니다: {chars}",
        )

    for block in timing.get("subtitleBlocks", []):
        lines = block.get("lines", block.get("text", "").split("\n"))
        if len(lines) > config.max_prayer_lines:
            raise SubtitleError(
                "SAFE_AREA_EXCEEDED",
                f"블록 {block.get('index')}의 라인 수({len(lines)})가 "
                f"safe area 최대 허용({config.max_prayer_lines})을 초과합니다.",
            )


# ─────────────────────── ASS sections ────────────────────────

def _script_info(config: SubtitleConfig) -> str:
    return (
        "[Script Info]\n"
        "; Generated by Gracetree Shorts Studio\n"
        "ScriptType: v4.00+\n"
        f"PlayResX: {config.play_res_x}\n"
        f"PlayResY: {config.play_res_y}\n"
        "WrapStyle: 0\n"
        "ScaledBorderAndShadow: yes\n"
    )


def _styles(config: SubtitleConfig) -> str:
    fmt = "Format: Name, Fontname, Fontsize, PrimaryColour, SecondaryColour, OutlineColour, BackColour, Bold, Italic, Underline, StrikeOut, ScaleX, ScaleY, Spacing, Angle, BorderStyle, Outline, Shadow, Alignment, MarginL, MarginR, MarginV, Encoding"
    mh = config.margin_h
    mv = config.margin_v_top

    def _style(name: str, size: int, color: str, alignment: int, margin_v: int) -> str:
        return (
            f"Style: {name},{config.font_name},{size},{color},&H000000FF,"
            f"{config.color_outline},{config.color_shadow},"
            f"-1,0,0,0,100,100,0,0,1,"
            f"{config.outline_thickness},{config.shadow_depth},"
            f"{alignment},{mh},{mh},{margin_v},1"
        )

    return (
        "[V4+ Styles]\n"
        f"{fmt}\n"
        f"{_style('Title', config.font_size_title, config.color_title, 8, mv)}\n"
        f"{_style('Scripture', config.font_size_scripture, config.color_scripture, 8, mv + config.font_size_title + 20)}\n"
        f"{_style('Prayer', config.font_size_prayer, config.color_prayer, 5, 0)}\n"
    )


def _dialogue(start: float, end: float, style: str, text: str, fade_in: int, fade_out: int) -> str:
    fad = f"{{\\fad({fade_in},{fade_out})}}"
    return (
        f"Dialogue: 0,{_format_time(start)},{_format_time(end)},"
        f"{style},,0,0,0,,{fad}{_escape_ass(text)}"
    )


def _events(
    script_ast: dict[str, Any],
    timing: dict[str, Any],
    config: SubtitleConfig,
) -> str:
    lines = [
        "[Events]",
        "Format: Layer, Start, End, Style, Name, MarginL, MarginR, MarginV, Effect, Text",
    ]

    timing_blocks = timing.get("subtitleBlocks", [])
    first_prayer_start = timing_blocks[0]["startTime"] if timing_blocks else timing.get("voiceOffset", 2.0)

    # Title and scripture: from 0 to first prayer start
    fi, fo = config.fade_in_ms, config.fade_out_ms
    lines.append(_dialogue(0.0, first_prayer_start, "Title", script_ast.get("title", ""), fi, fo))
    lines.append(_dialogue(0.0, first_prayer_start, "Scripture", script_ast.get("scripture", ""), fi, fo))

    # Prayer blocks
    for i, block in enumerate(timing_blocks):
        is_last = (i == len(timing_blocks) - 1)
        text = block.get("text", "")
        start = block["startTime"]
        end = block["endTime"]

        if is_last and _is_amen_text(text):
            end += config.amen_hold_seconds
            fade_out = config.amen_fade_out_ms
        else:
            fade_out = fo

        lines.append(_dialogue(start, end, "Prayer", text, fi, fade_out))

    return "\n".join(lines) + "\n"


# ─────────────────────── public API ────────────────────────

def generate_ass(
    script_ast: dict[str, Any],
    timing: dict[str, Any],
    config: SubtitleConfig = DEFAULT_SUBTITLE_CONFIG,
    font_path: Path | None = None,
) -> str:
    """Generate ASS subtitle content string.

    Parameters
    ----------
    script_ast: ScriptAstDto dict from Story 2.2 parser.
    timing: timing.json dict from Story 2.3 aligner.
    config: layout and styling config.
    font_path: optional path for font existence check (None = skip check).

    Returns
    -------
    ASS content as a UTF-8 string.

    Raises
    ------
    SubtitleError: FONT_NOT_FOUND, GLYPH_NOT_SUPPORTED, SAFE_AREA_EXCEEDED
    """
    _validate(script_ast, timing, config, font_path)
    parts = [
        _script_info(config),
        _styles(config),
        _events(script_ast, timing, config),
    ]
    return "\n".join(parts)


def generate_subtitles(
    script_ast: dict[str, Any],
    timing: dict[str, Any],
    attempt_dir: Path,
    config: SubtitleConfig = DEFAULT_SUBTITLE_CONFIG,
    font_path: Path | None = None,
) -> Path:
    """Generate and write subtitles.ass to attempt_dir.

    Returns path to the written file.
    Raises SubtitleError on validation failure.
    """
    content = generate_ass(script_ast, timing, config, font_path)
    out = attempt_dir / "subtitles.ass"
    out.write_text(content, encoding="utf-8")
    return out
